import { ModuleTypes } from "core";

export const ModuleConfig: {[sectionID: string]: { module: ModuleTypes, sectionID: string }} =
{
        B0: { module: "B", sectionID: "B0" },
        B1: { module: "B", sectionID: "B1" },
        B2: { module: "B", sectionID: "B2" },
        B3: { module: "B", sectionID: "B3" },
        B4: { module: "B", sectionID: "B4" },
        B5: { module: "B", sectionID: "B5" },
        B6: { module: "B", sectionID: "B6" },
        B7: { module: "B", sectionID: "B7" },
        B8: { module: "B", sectionID: "B8" },
        B9: { module: "B", sectionID: "B9" },
        G0: { module: "G", sectionID: "G0" },
        G1: { module: "G", sectionID: "G1" },
        G2: { module: "G", sectionID: "G2" },
        G3: { module: "G", sectionID: "G3" },
        G4: { module: "G", sectionID: "G4" },
        G5: { module: "G", sectionID: "G5" },
        G6: { module: "G", sectionID: "G6" },
        G7: { module: "G", sectionID: "G7" },
        G8: { module: "G", sectionID: "G8" },
        G9: { module: "G", sectionID: "G9" },
        C0: { module: "C", sectionID: "C0" },
        C1: { module: "C", sectionID: "C1" },
        C2: { module: "C", sectionID: "C2" },
        C3: { module: "C", sectionID: "C3" },
        C4: { module: "C", sectionID: "C4" },
        C5: { module: "C", sectionID: "C5" },
        C6: { module: "C", sectionID: "C6" },
        C7: { module: "C", sectionID: "C7" },
        C8: { module: "C", sectionID: "C8" },
        C9: { module: "C", sectionID: "C9" },
}